### ISSUE TITLE
Not enforcing role selection

### ISSUE THREAD

**Issue by JoLBree** [SaturdayNeighborhoodHealthClinic/osler#122]
In the role-choice page, would spit out a stack trace with a MultiValueDictKeyError if the submit button was clicked without selecting a role.

**Comment by justinrporter** [comment]
Full stack trace, for reference:

```
Internal Server Error: /pttrack/choose-role/ 
Traceback (most recent call last): 
File "/home/washu/.virtualenvs/osler/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response 
response = wrapped_callback(request, *callback_args, **callback_kwargs) 
File "/home/washu/.virtualenvs/osler/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view 
return view_func(request, *args, **kwargs) 
File "/home/washu/.virtualenvs/osler/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view 
return view_func(request, *args, **kwargs) 
File "/home/washu/.virtualenvs/osler/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view 
return view_func(request, *args, **kwargs) 
File "/home/washu/clintools/pttrack/views.py", line 269, in choose_clintype 
request.session['clintype_pk'] = request.POST[RADIO_CHOICE_KEY] 
File "/home/washu/.virtualenvs/osler/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__ 
raise MultiValueDictKeyError(repr(key)) 
MultiValueDictKeyError: "'radio-roles'" 

Request repr(): 
<WSGIRequest 
path:/pttrack/choose-role/, 
GET:<QueryDict: {u'next': [u'/pttrack/']}>, 
POST:<QueryDict: {u'csrfmiddlewaretoken': [u'Xc6c7ciMtI2NVwjbR9KRbgn6QUZWmbd4']}>, 
COOKIES:{'csrftoken': 'Xc6c7ciMtI2NVwjbR9KRbgn6QUZWmbd4', 
'sessionid': 'r2ew6mk7dexwgywlc12uug846fmepotw'}, 
META:{'CONTENT_LENGTH': '52', 
'CONTENT_TYPE': 'application/x-www-form-urlencoded', 
u'CSRF_COOKIE': u'Xc6c7ciMtI2NVwjbR9KRbgn6QUZWmbd4', 
'DOCUMENT_ROOT': '/etc/apache2/htdocs', 
'GATEWAY_INTERFACE': 'CGI/1.1', 
'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 
'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8', 
'HTTP_CACHE_CONTROL': 'max-age=0', 
'HTTP_CONNECTION': 'Keep-Alive', 
'HTTP_COOKIE': 'sessionid=r2ew6mk7dexwgywlc12uug846fmepotw; csrftoken=Xc6c7ciMtI2NVwjbR9KRbgn6QUZWmbd4', 
'HTTP_HOST': 'osler.wustl.edu:443', 
'HTTP_ORIGIN': 'https://osler.wustl.edu', 
'HTTP_REFERER': 'https://osler.wustl.edu/pttrack/choose-role/?next=/pttrack/', 
'HTTP_REVERSE_VIA': 'WUSM-TMG-01', 
'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 
'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36', 
'PATH_INFO': u'/pttrack/choose-role/', 
'PATH_TRANSLATED': '/home/washu/clintools/osler/wsgi.py/pttrack/choose-role/', 
'QUERY_STRING': 'next=/pttrack/', 
'REMOTE_ADDR': '10.39.12.78', 
'REMOTE_PORT': '27068', 
'REQUEST_METHOD': 'POST', 
'REQUEST_URI': '/pttrack/choose-role/?next=/pttrack/', 
'SCRIPT_FILENAME': '/home/washu/clintools/osler/wsgi.py', 
'SCRIPT_NAME': u'', 
'SERVER_ADDR': '10.39.245.55', 
'SERVER_ADMIN': 'snhc@wusm.wustl.edu', 
'SERVER_NAME': 'osler.wustl.edu', 
'SERVER_PORT': '443', 
'SERVER_PROTOCOL': 'HTTP/1.1', 
'SERVER_SIGNATURE': '<address>Apache Server at osler.wustl.edu Port 443</address>\n', 
'SERVER_SOFTWARE': 'Apache', 
'mod_wsgi.application_group': '', 
'mod_wsgi.callable_object': 'application', 
'mod_wsgi.handler_script': '', 
'mod_wsgi.input_chunked': '0', 
'mod_wsgi.listener_host': '', 
'mod_wsgi.listener_port': '80', 
'mod_wsgi.process_group': '', 
'mod_wsgi.request_handler': 'wsgi-script', 
'mod_wsgi.script_reloading': '1', 
'mod_wsgi.version': (3, 3), 
'wsgi.errors': <mod_wsgi.Log object at 0x7f4440ed7ab0>, 
'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f44047e0648>, 
'wsgi.input': <mod_wsgi.Input object at 0x7f43f466b630>, 
'wsgi.multiprocess': True, 
'wsgi.multithread': True, 
'wsgi.run_once': False, 
'wsgi.url_scheme': 'http', 
'wsgi.version': (1, 1)}> 
```
